### ISSUE TITLE
Fails to build on ppc64le (musl)

### ISSUE THREAD

**Issue by tmpfile** [libunwind/libunwind#33]
libunwind fails to build from source on Alpine Linux ppc64le port, a musl-based system.

The log: http://sprunge.us/ibAL

**Comment by djwatson** [comment]
I've seen this conflicting mcontext definition several times now (previously mostly on cross compiles), but haven't been able to track it down

**Comment by djwatson** [comment]
Possibly some arches on musl need to export the register definitions?

https://github.com/openwrt/openwrt/blob/master/package/libs/libunwind/patches/003-fix-missing-ef_reg-defs-with-musl.patch

**Comment by rgdoliveira** [comment]
I took a quickly look in libunwind code and tried to build  it in Alpine ppc64le. I was able to do some fixes on it [1]. Note that it is missing the #ifdefs as I was trying to make the build work.

But now it fails with the error:

Gperf-simple.o:` In function `measure_init':
/home/alpine/repos/libunwind/tests/Gperf-simple.c:180: undefined reference to `getcontext'
/home/alpine/repos/libunwind/tests/Gperf-simple.c:207: undefined reference to `getcontext'
Gperf-simple.o: In function `measure_unwind':
/home/alpine/repos/libunwind/tests/Gperf-simple.c:65: undefined reference to `getcontext'
../src/.libs/libunwind-ppc64.so: undefined reference to `setcontext'
collect2: error: ld returned 1 exit status

Both getcontext() and setcontext() are not implemented in musl libc [2]. The build works on Alpine x86_64 because it implements the getcontext and setcontext behaviours in .S files (e.g: ./src/x86_64/getcontext.S)

---
[1] - http://termbin.com/74ib
[2] - http://www.openwall.com/lists/musl/2016/02/04/4

**Comment by djwatson** [comment]
On 08/26/17 09:25 PM, Roberto Oliveira wrote:
> I took a quickly look in libunwind code and tried to build  it in Alpine ppc64le. I was able to do some fixes on it [1]. Note that it is missing the #ifdefs as I was trying to make the build work.
> 
> But now it fails with the error:
> 
> Gperf-simple.o:` In function `measure_init':
> /home/alpine/repos/libunwind/tests/Gperf-simple.c:180: undefined reference to `getcontext'
> /home/alpine/repos/libunwind/tests/Gperf-simple.c:207: undefined reference to `getcontext'
> Gperf-simple.o: In function `measure_unwind':
> /home/alpine/repos/libunwind/tests/Gperf-simple.c:65: undefined reference to `getcontext'
> ../src/.libs/libunwind-ppc64.so: undefined reference to `setcontext'
> collect2: error: ld returned 1 exit status
> 
> Both getcontext() and setcontext() are not implemented in musl libc [2]. The build works on Alpine x86_64 because it implements the getcontext and setcontext behaviours in .S files (e.g: ./src/x86_64/getcontext.S)

If you want to provide patches for getcontext and setcontext, I'd be
happy to merge them (and I'll look at adding ifdefs and merging your
changes above).

**Comment by djwatson** [comment]
will track in #69
