### ISSUE TITLE
Extraneous characters in symbol names

### ISSUE THREAD

**Issue by wyattbiker** [libunwind/libunwind#424]
```c++
printf("0x%lx:", (unsigned long)pc);
if (unw_get_proc_name(&cursor, sym, sizeof(sym), &offset) == 0) {
    printf(" (%s)\n", sym);       
....
....
```

What are the **_Znn** and also a **v** at the end of the symbol name? They appear on ever symbol except main. I am on Mac OS X. Any way to get rid of them?

```
0x100003d09: (_Z9some_funcv)
0x100003ce9: (_Z19is_anything_pressedv)
0x100003ecb: (main)
```

**Comment by bregma** [comment]
Those look like C++ names mangled under the [Itanium ABi spec](https://itanium-cxx-abi.github.io/cxx-abi/abi-mangling.html). Name mangling is a way of encoding type information into the symbol since that information is significant in C++ and is pretty much specific to the toolchain and OS used. libunwind doesn't do name demangling: you'll want to use one of the available platform-specific demangling libraries out there for that. You could probably also pass the output through a utility like **c++filt** if it's available on your development host.
