### ISSUE TITLE
How to add process map and backing file after commit e96db56e586ad7a1c8d27593382b365f775a398f

### ISSUE THREAD

**Issue by egtvedt** [libunwind/libunwind#538]
In commit e96db56e586ad7a1c8d27593382b365f775a398f ("Stop assuming .text and .eh_frame segment") the function _UCD_add_backing_file_at_vaddr() was removed and I can not immediate see how to add address mapping to backing files.

The commit was done for solving issue #363, just mentioning it for consistency.

Before libunwind 1.7.0 release I would do the following when unwinding a core dump:
- parse the ELF header
- find NT_FILE section
- read out process map
- pass in mapping of process vm_start and file path through the _UCD_add_backing_file_at_vaddr() function

I have a feeling parsing NT_FILE section, mapping process and backing files is handled different now, but I can not immediate see how. The run-coredump-unwind example did delete the _UCD_add_backing_file_at_vaddr() step, leading me to think _UCD_create() should handle this now?

Update: i ran make check on v1.7.0 tag on Ubuntu 23.04 based system, and run-coredump-unwind fails with
```
Segmentation fault (core dumped)
FAILURE: procedure names are missing/incorrect
FAIL run-coredump-unwind (exit status: 255)
```

Note: I had to alter the `ulimit -c` call, increasing it to 1000000, since Ubuntu 23.04 generates far bigger core files now. This test example core file is 442368 bytes on my computer.

**Comment by bregma** [comment]
Yes, because there is no longer a 1:1 mapping between files and LOAD segments, and between the executable LOAD segment containing the .text sections and the RO LOAD segment containing the .eh_frame sections,  and because the executable LOAD segment is not always loaded first in memory, simply mapping a file to the first LOAD segment encountered was broken. It's now mapped though `ucd_file_map()` to handle the many-to-one relationship, and that's done automatically while processing all the PT_NOTE sections in the core file. The changes made to the underlying ELF file layout were made by upstream linker folks (GNU binutils and LLVM lld) for reasons of improved security.

The `run-coredump-unwind` test [passes in CI on Ubuntu 22.04 LTS x86_64](https://github.com/libunwind/libunwind/actions/runs/5169015945).  If there is a regression on Ubuntu 23.04 that's a bug and we'll need more information.

**Comment by egtvedt** [comment]
@bregma thank you for the details. Do you think this behavior depends on linking with latest binutils. What I see locally is that I do get unwinding of library functions, but the actual program crashing is not able to unwind.

Will try to experiment a bit locally with linker flags and/or upgrading to latest binutils.

I will also create a new issue for what I see on Ubuntu 23.04, will retry running make check on HEAD.

**Comment by bregma** [comment]
Did you build the crashing program with debug symbols?

**Comment by egtvedt** [comment]
> Did you build the crashing program with debug symbols?

The only change I did was switch from libunwind v1.6.1 to v1.7.0.

I do not build with debug symbols, I compile with -funwind-tables.

**Comment by egtvedt** [comment]
Just to finish off this conversation, I upgraded binutils from 2.38 to 2.41, and I can unwind using libunwind 1.7.x releases.
