### ISSUE TITLE
test build failures: Lperf-simple.o: cannot make copy relocation for protected symbol '_ULx86_64_local_addr_space', defined in ../src/.libs/libunwind.so

### ISSUE THREAD

**Issue by milianw** [libunwind/libunwind#58]
I just tried to build current git master and get the following build errors in the tests:

```
make[1]: Entering directory '/ssd/milian/projects/build/libunwind/tests'
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fexceptions -Wall -Wsign-compare   -o Gperf-simple Gperf-simple.o ../src/libunwind-x86_64.la ../src/libunwind.la 
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fexceptions -Wall -Wsign-compare   -o Lperf-simple Lperf-simple.o ../src/libunwind.la 
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fexceptions -Wall -Wsign-compare   -o Gperf-trace Gperf-trace.o ../src/libunwind-x86_64.la ../src/libunwind.la 
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fexceptions -Wall -Wsign-compare   -o Lperf-trace Lperf-trace.o ../src/libunwind.la 
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fexceptions -Wall -Wsign-compare   -o test-coredump-unwind test-coredump-unwind.o ../src/libunwind-coredump.la ../src/libunwind-x86_64.la  
libtool: link: gcc -g -O2 -fexceptions -Wall -Wsign-compare -o .libs/Lperf-simple Lperf-simple.o  ../src/.libs/libunwind.so -lc -lgcc_s -llzma -Wl,-rpath -Wl,/home/milian/projects/compiled/other/lib
libtool: link: gcc -g -O2 -fexceptions -Wall -Wsign-compare -o .libs/Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-x86_64.so /home/milian/projects/build/libunwind/src/.libs/libunwind.so ../src/.libs/libunwind.so -lc -lgcc_s -llzma -Wl,-rpath -Wl,/home/milian/projects/compiled/other/lib
libtool: link: gcc -g -O2 -fexceptions -Wall -Wsign-compare -o .libs/Lperf-trace Lperf-trace.o  ../src/.libs/libunwind.so -lc -lgcc_s -llzma -Wl,-rpath -Wl,/home/milian/projects/compiled/other/lib
libtool: link: gcc -g -O2 -fexceptions -Wall -Wsign-compare -o .libs/Gperf-simple Gperf-simple.o  ../src/.libs/libunwind-x86_64.so /home/milian/projects/build/libunwind/src/.libs/libunwind.so ../src/.libs/libunwind.so -lc -lgcc_s -llzma -Wl,-rpath -Wl,/home/milian/projects/compiled/other/lib
/home/milian/.bin/ld: error: Lperf-simple.o: cannot make copy relocation for protected symbol '_ULx86_64_local_addr_space', defined in ../src/.libs/libunwind.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1125: Lperf-simple] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: link: gcc -g -O2 -fexceptions -Wall -Wsign-compare -o .libs/test-coredump-unwind test-coredump-unwind.o  ../src/.libs/libunwind-coredump.so ../src/.libs/libunwind-x86_64.so /home/milian/projects/build/libunwind/src/.libs/libunwind.so -lgcc_s -llzma -lc -Wl,-rpath -Wl,/home/milian/projects/compiled/other/lib
/home/milian/.bin/ld: error: Gperf-trace.o: cannot make copy relocation for protected symbol '_Ux86_64_local_addr_space', defined in ../src/.libs/libunwind-x86_64.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1073: Gperf-trace] Error 1
/home/milian/.bin/ld: error: Lperf-trace.o: cannot make copy relocation for protected symbol '_ULx86_64_local_addr_space', defined in ../src/.libs/libunwind.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1129: Lperf-trace] Error 1
/home/milian/.bin/ld: error: Gperf-simple.o: cannot make copy relocation for protected symbol '_Ux86_64_local_addr_space', defined in ../src/.libs/libunwind-x86_64.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1069: Gperf-simple] Error 1
/home/milian/.bin/ld: error: test-coredump-unwind.o: cannot make copy relocation for protected symbol '_UCD_accessors', defined in ../src/.libs/libunwind-coredump.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1225: test-coredump-unwind] Error 1
```

Any idea what that might trigger? I'm on ArchLinux with gcc 7.2.0 and use gold 1.14 from binutils 2.29.1 for linking.

**Comment by djwatson** [comment]
This is the first I've seen of it.  Others seem to report this is an issue when linking with gold and visibility:

https://patchwork.openembedded.org/patch/142239/
https://patchwork.openembedded.org/patch/132005/

I don't see any solutions posted though, besides either linking with ld, or disabling visibility

**Comment by milianw** [comment]
Considering it only fails for the tests, I just want to check: Is the symbol maybe compiled into the test and then linked to it again? Maybe that's the issue? I mean, I use gold for everything else and it works nicely, including KDE/Qt which also heavily uses symbol visibility, and it works well there.

**Comment by emaste** [comment]
This issue also affects linking with lld: https://bugs.freebsd.org/219524
It's probably just incorrect for these symbols to have protected visibility

Useful reference links:
https://www.airs.com/blog/archives/307
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=19520

**Comment by emaste** [comment]
For reference, in FreeBSD we've now forced libunwind to avoid linking with lld.
https://svnweb.freebsd.org/changeset/ports/456743

I think the short version of this bug is that setting protected visibility on preemptible symbols is underspecified and there is no clear consensus on the correct behaviour among those working on tool chains. I believe libunwind's use of protected visibility is relying on an implementation detail of GNU ld.bfd, and is not guaranteed to continue working.

**Comment by djwatson** [comment]
So it sounds like the correct solution is to make unw_local_addr_space and coredump accessors public , and alias internal HIDDEN versions, and renaming all the internal variables to a new name?  I'll put up a diff for that.

**Comment by emaste** [comment]
That seems reasonable although it's not just those symbols - for example, Gperf-simple.c fails for me with lld like so:
```
/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_init_local
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:195
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_init_local
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:219
>>>               Gperf-simple.o:(main)
/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_local_addr_space
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:254
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_set_caching_policy
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:254
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_local_addr_space
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:257 
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_set_caching_policy
>>> defined in ../src/.libs/libunwind-x86_64.so 
>>> referenced by Gperf-simple.c:257
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_local_addr_space
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:260 
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_set_caching_policy
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:260
>>>               Gperf-simple.o:(main)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_init_local
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:66
>>>               Gperf-simple.o:(measure_unwind)

/usr/bin/ld: error: cannot preempt symbol: _Ux86_64_step
>>> defined in ../src/.libs/libunwind-x86_64.so
>>> referenced by Gperf-simple.c:73
>>>               Gperf-simple.o:(measure_unwind)
```

**Comment by djwatson** [comment]
Ok, all the protected symbols will be renamed then, and completely do away with PROTECTED.

**Comment by espindola** [comment]
Replacing the proteced symbols with internal + alias will work for both gold and lld. It will also be more efficient when using gcc + bfd ld.
 
Now to explain what is going on.

When a library both exports and uses a symbol, either the library or the program using it must use a got entry to access the symbol. If the library uses the .got entry, the main program can have a copy relocation and the library .got entry will refer to that.

For default visibility symbols, the library is the one using the .got.

For hidden + alias, the library will access the hidden symbol directly and the main program might have a copy relocation to the alias. The result is that by using hidden + alias one is explicitly abdicating pointer equality. The main program and the library will see different copies of the symbol.

Unfortunately currently ELF has no flag to state that a given symbol doesn't require pointer equality. This means that the toolchain has to be conservative and assume it is important.

One way to do it (gold and lld) is to refuse to produce copy relocations to protected symbols.

Another way is to assume the compiler uses a got entry to access protected visibility (bfd) symbols. IMHO that is unfortunate as it prevents libraries from directly accessing their own symbols. Both COFF and MachO allow shared libraries to efficiently access their symbols. This is why changing to hidden+alias will improve code quality with gcc.

I hope to make protected visibility easier to use in a few steps:
* Add an option to lld to explicitly allow it to ignore pointer equality.
* Try to define a flag for ELF symbols. This could be set via an attribute or automatically for some compiler created symbols (c++ virtual functions for example).
* Add a flag to clang for it to not assume it can create copy relocations. This is how MachO works and is pretty efficient since the linker can relax got loads for symbols that end up being in the main executable.
