### ISSUE TITLE
Ltest-init-local-signal and Gtest-concurrent failed on aarch64

### ISSUE THREAD

**Issue by ziyangc97** [libunwind/libunwind#591]
hi dear libunwind maintainers

I am using:
glibc-2.28
gcc-7.3
libunwind-1.3.2 & libunwind-1.6.2 and failed on these testcases:

../config/test-driver: line 95:  7989 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Gtest-concurrent
../config/test-driver: line 95:  8023 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-concurrent
../config/test-driver: line 95:  8181 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-init-local-signal

The direct reason of segmentation fault is unw_step() access a 0x0 memory address.
I use gdb to trace the stackframe and found that the memory address of cursor->dwarf.ip is 0.

Q1: In what circumstances the cursor->dward.ip will be 0? Is this an expected scenario?
Q2: Does the libunwind community have plan to backport commits from master branch to old stable version such as libunwind-1.3.2 or libunwind-1.6.2 ? I see a lot of aarch64 bugfix and enhancement commits in master branch.

**Comment by bregma** [comment]
The dwarf.ip value can become 0 when reaching the end of the stack on some aarch64 ABIs. I'm not sure if that's normal on GNU/Linux but I expect so given it's defined in the ARM ABI. If I recall that was a case that was missed by some of the older implementation code which instead relied exclusively on the DWARF information and was fixed on master.

I don't think anyone has any intention of backporting all the recent development fixes to older releases, mostly because the community is very small and the CI used for older releases is no longer available (nor was it very complete or, obviously, effective).

Would it be possible for you to update to a newer release of libunwind instead? Branching for v1.8 should be coming soon.
