### ISSUE TITLE
libunwind.so.8.0.1 lacks _Unwind* symbols on most Linux distributions

### ISSUE THREAD

**Issue by REmerald** [libunwind/libunwind#615]
On Debian and Alpine (`libunwind8_1.6.2-3_amd64.deb` and `libunwind-1.6.2-r3.apk` respectively), the `strings libunwind.so.8.0.1 | grep '_Unwind'` returns:
```
__libunwind_Unwind_Backtrace
__libunwind_Unwind_DeleteException
__libunwind_Unwind_FindEnclosingFunction
__libunwind_Unwind_ForcedUnwind
__libunwind_Unwind_GetBSP
__libunwind_Unwind_GetCFA
__libunwind_Unwind_GetDataRelBase
__libunwind_Unwind_GetGR
__libunwind_Unwind_GetIP
__libunwind_Unwind_GetLanguageSpecificData
__libunwind_Unwind_GetRegionStart
__libunwind_Unwind_GetTextRelBase
__libunwind_Unwind_RaiseException
__libunwind_Unwind_Resume
__libunwind_Unwind_Resume_or_Rethrow
__libunwind_Unwind_SetGR
__libunwind_Unwind_SetIP
__libunwind_Unwind_GetIPInfo
```
Thus, using `clang -rtlib=compiler-rt -unwindlib=libunwind`  with sanitizers compiles programs successfully.

But on other distros I checked (Arch, Void, openSUSE, Fedora, RHEL family, Slackware) the command returns nothing (because these symbols are absent, I checked manually). So, any linker invoked by clang fails, claiming it can't find `_Unwind_Backtrace` and `_Unwind_GetIP`. See https://github.com/llvm/llvm-project/issues/65796#issuecomment-1716486460.

UPD:
Related to #124?

If there will be a fix, will it be possible to also apply it to e.g. `1.6.2` and not just for git or future version? Most distros are still staying on `1.6.2` (some on `1.5.0`).

**Comment by REmerald** [comment]
Hmm, the problem seems to be caused by the absence of `--enable-cxx-exceptions` during build.

Alpine and Debian did include them:
https://github.com/alpinelinux/aports/blob/master/main/libunwind/APKBUILD#L21
`libunwind_1.6.2-3.debian.tar.xz/debian/rules`
```
ifneq (,$(filter $(DEB_HOST_ARCH), amd64 i386))
  CXX_EXCEPTIONS=--enable-cxx-exceptions
endif
```
While others did not:
https://gitlab.archlinux.org/archlinux/packaging/packages/libunwind/-/blob/main/PKGBUILD?ref_type=heads#L23
https://src.fedoraproject.org/rpms/libunwind/blob/f38/f/libunwind.spec#_88
https://build.opensuse.org/package/view_file/openSUSE:Factory/libunwind/libunwind.spec?expand=1
https://src.fedoraproject.org/rpms/libunwind/blob/epel9/f/libunwind.spec#_48
And Void explicitly didn't include it for a weird unexplained reason:
https://github.com/void-linux/void-packages/blob/master/srcpkgs/libunwind/template#L17

Is there any reason `cxx_exceptions` aren't activated by default?

For now, it seems that in order to fix the current versions I need to create a bugreport for each distro individually :weary:...
Is there a way for you guys to make it faster because you are the developers?

**Comment by bregma** [comment]
Providing the C++ (and Ada, etc.) language runtime support functions is not enabled by default because under most circumstances the specialized language runtime libraries are provided by the toolchain. Playing with language runtimes is a pretty specialized application. Generally people experimenting with alternative language runtimes don't need a general-purpose environment like a GNU/Linux distribution to provide their specialized dependencies and users of general-purpose environments don't want their space unexpectedly polluted with third-party replacements for stuff they use every day, so the distro decision to not enable it is sensible.

Whether a GNU/Linux distribution chooses to enable that optional functionality is decision that is distro-specific. There is nothing the libunwind project can do.

Closing as not a libunwind bug.
